#!/usr/bin/env ruby
require 'mkmf'
system( "ln -sf ../mltpp.i mltpp.i" )
system( "swig -c++ -ruby -I../../mlt++ `pkg-config mlt-framework --cflags` mltpp.i" )
$CFLAGS += " -I../../mlt++ `pkg-config mlt-framework --cflags`"
$LDFLAGS += " -L../../mlt++ -lmlt++"
create_makefile('mlt')
system( 'make' )
