#!/usr/bin/env ruby
require 'mkmf'
if ARGV.shift == 'clean'
  system( "rm -f *.cxx *.so *.o mlt.i ../.ruby Makefile" )
  exit 0
end
system( "ln -sf ../mlt.i" )
system( "swig -c++ -ruby -I../../mlt++ -I../.. mlt.i" )
$CFLAGS += " -I../.. " + (ENV.has_key?('CXXFLAGS')? ENV['CXXFLAGS'] : '')
$LDFLAGS += " -L../../mlt++ -lmlt++"
create_makefile('mlt')
system( "make" )
