#!/usr/bin/env ruby
require 'mkmf'
system( "ln -sf ../mlt.i" )
system( "swig -c++ -ruby -I../../mlt++ -I../.. mlt.i" )
$CFLAGS += "-I../.."
$LDFLAGS += " -L../../mlt++ -lmlt++"
create_makefile('mlt')
system( 'make' )
