#!/bin/sh

if [ "$1" = "clean" ]
then
	( cd `dirname $0`; rm -f *.cpp *.so *.o mlt.i ../.php mlt.php *.h )
	exit 0
fi


ln -sf ../mlt.i
swig -c++ -I../../mlt++ -I../.. -php5 -noproxy mlt.i
g++ -fPIC -DPIC -D_GNU_SOURCE -c -rdynamic -pthread -I../.. `php-config --includes` mlt_wrap.cpp
g++ -shared mlt_wrap.o -L../../mlt++ -lmlt++ -o mlt.so || exit $?
