/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Jit.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Jit.pb-c.h"
void   jit__init
                     (Jit         *message)
{
  static const Jit init_value = JIT__INIT;
  *message = init_value;
}
size_t jit__get_packed_size
                     (const Jit *message)
{
  assert(message->base.descriptor == &jit__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t jit__pack
                     (const Jit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &jit__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t jit__pack_to_buffer
                     (const Jit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &jit__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Jit *
       jit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Jit *)
     protobuf_c_message_unpack (&jit__descriptor,
                                allocator, len, data);
}
void   jit__free_unpacked
                     (Jit *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &jit__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   media_info__init
                     (MediaInfo         *message)
{
  static const MediaInfo init_value = MEDIA_INFO__INIT;
  *message = init_value;
}
size_t media_info__get_packed_size
                     (const MediaInfo *message)
{
  assert(message->base.descriptor == &media_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t media_info__pack
                     (const MediaInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &media_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t media_info__pack_to_buffer
                     (const MediaInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &media_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MediaInfo *
       media_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MediaInfo *)
     protobuf_c_message_unpack (&media_info__descriptor,
                                allocator, len, data);
}
void   media_info__free_unpacked
                     (MediaInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &media_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stream__init
                     (Stream         *message)
{
  static const Stream init_value = STREAM__INIT;
  *message = init_value;
}
size_t stream__get_packed_size
                     (const Stream *message)
{
  assert(message->base.descriptor == &stream__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stream__pack
                     (const Stream *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stream__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stream__pack_to_buffer
                     (const Stream *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stream__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Stream *
       stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Stream *)
     protobuf_c_message_unpack (&stream__descriptor,
                                allocator, len, data);
}
void   stream__free_unpacked
                     (Stream *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stream__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   audio_stream__init
                     (AudioStream         *message)
{
  static const AudioStream init_value = AUDIO_STREAM__INIT;
  *message = init_value;
}
size_t audio_stream__get_packed_size
                     (const AudioStream *message)
{
  assert(message->base.descriptor == &audio_stream__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t audio_stream__pack
                     (const AudioStream *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &audio_stream__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t audio_stream__pack_to_buffer
                     (const AudioStream *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &audio_stream__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AudioStream *
       audio_stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AudioStream *)
     protobuf_c_message_unpack (&audio_stream__descriptor,
                                allocator, len, data);
}
void   audio_stream__free_unpacked
                     (AudioStream *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &audio_stream__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor jit__field_descriptors[3] =
{
  {
    "position",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Jit, position),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "playback",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Jit, playback),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mediaInfo",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Jit, mediainfo),
    &media_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned jit__field_indices_by_name[] = {
  2,   /* field[2] = mediaInfo */
  1,   /* field[1] = playback */
  0,   /* field[0] = position */
};
static const ProtobufCIntRange jit__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor jit__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Jit",
  "Jit",
  "Jit",
  "",
  sizeof(Jit),
  3,
  jit__field_descriptors,
  jit__field_indices_by_name,
  1,  jit__number_ranges,
  (ProtobufCMessageInit) jit__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor media_info__field_descriptors[1] =
{
  {
    "streams",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MediaInfo, n_streams),
    offsetof(MediaInfo, streams),
    &stream__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned media_info__field_indices_by_name[] = {
  0,   /* field[0] = streams */
};
static const ProtobufCIntRange media_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor media_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MediaInfo",
  "MediaInfo",
  "MediaInfo",
  "",
  sizeof(MediaInfo),
  1,
  media_info__field_descriptors,
  media_info__field_indices_by_name,
  1,  media_info__number_ranges,
  (ProtobufCMessageInit) media_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stream__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Stream, type),
    &stream_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Stream, audio),
    &audio_stream__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stream__field_indices_by_name[] = {
  1,   /* field[1] = audio */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange stream__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor stream__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Stream",
  "Stream",
  "Stream",
  "",
  sizeof(Stream),
  2,
  stream__field_descriptors,
  stream__field_indices_by_name,
  1,  stream__number_ranges,
  (ProtobufCMessageInit) stream__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor audio_stream__field_descriptors[1] =
{
  {
    "channels",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AudioStream, channels),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned audio_stream__field_indices_by_name[] = {
  0,   /* field[0] = channels */
};
static const ProtobufCIntRange audio_stream__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor audio_stream__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AudioStream",
  "AudioStream",
  "AudioStream",
  "",
  sizeof(AudioStream),
  1,
  audio_stream__field_descriptors,
  audio_stream__field_indices_by_name,
  1,  audio_stream__number_ranges,
  (ProtobufCMessageInit) audio_stream__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue stream_type__enum_values_by_number[3] =
{
  { "UNKNOWN", "STREAM_TYPE__UNKNOWN", 0 },
  { "AUDIO", "STREAM_TYPE__AUDIO", 1 },
  { "VIDEO", "STREAM_TYPE__VIDEO", 2 },
};
static const ProtobufCIntRange stream_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex stream_type__enum_values_by_name[3] =
{
  { "AUDIO", 1 },
  { "UNKNOWN", 0 },
  { "VIDEO", 2 },
};
const ProtobufCEnumDescriptor stream_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "StreamType",
  "StreamType",
  "StreamType",
  "",
  3,
  stream_type__enum_values_by_number,
  3,
  stream_type__enum_values_by_name,
  1,
  stream_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
