/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Jit.proto */

#ifndef PROTOBUF_C_Jit_2eproto__INCLUDED
#define PROTOBUF_C_Jit_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Jit Jit;
typedef struct _MediaInfo MediaInfo;
typedef struct _Stream Stream;
typedef struct _AudioStream AudioStream;


/* --- enums --- */

typedef enum _StreamType {
  STREAM_TYPE__UNKNOWN = 0,
  STREAM_TYPE__AUDIO = 1,
  STREAM_TYPE__VIDEO = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STREAM_TYPE)
} StreamType;

/* --- messages --- */

struct  _Jit
{
  ProtobufCMessage base;
  int64_t position;
  float playback;
  MediaInfo *mediainfo;
};
#define JIT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&jit__descriptor) \
    , 0, 0, NULL }


struct  _MediaInfo
{
  ProtobufCMessage base;
  size_t n_streams;
  Stream **streams;
};
#define MEDIA_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&media_info__descriptor) \
    , 0,NULL }


struct  _Stream
{
  ProtobufCMessage base;
  StreamType type;
  AudioStream *audio;
};
#define STREAM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&stream__descriptor) \
    , STREAM_TYPE__UNKNOWN, NULL }


struct  _AudioStream
{
  ProtobufCMessage base;
  int32_t channels;
};
#define AUDIO_STREAM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio_stream__descriptor) \
    , 0 }


/* Jit methods */
void   jit__init
                     (Jit         *message);
size_t jit__get_packed_size
                     (const Jit   *message);
size_t jit__pack
                     (const Jit   *message,
                      uint8_t             *out);
size_t jit__pack_to_buffer
                     (const Jit   *message,
                      ProtobufCBuffer     *buffer);
Jit *
       jit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   jit__free_unpacked
                     (Jit *message,
                      ProtobufCAllocator *allocator);
/* MediaInfo methods */
void   media_info__init
                     (MediaInfo         *message);
size_t media_info__get_packed_size
                     (const MediaInfo   *message);
size_t media_info__pack
                     (const MediaInfo   *message,
                      uint8_t             *out);
size_t media_info__pack_to_buffer
                     (const MediaInfo   *message,
                      ProtobufCBuffer     *buffer);
MediaInfo *
       media_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   media_info__free_unpacked
                     (MediaInfo *message,
                      ProtobufCAllocator *allocator);
/* Stream methods */
void   stream__init
                     (Stream         *message);
size_t stream__get_packed_size
                     (const Stream   *message);
size_t stream__pack
                     (const Stream   *message,
                      uint8_t             *out);
size_t stream__pack_to_buffer
                     (const Stream   *message,
                      ProtobufCBuffer     *buffer);
Stream *
       stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   stream__free_unpacked
                     (Stream *message,
                      ProtobufCAllocator *allocator);
/* AudioStream methods */
void   audio_stream__init
                     (AudioStream         *message);
size_t audio_stream__get_packed_size
                     (const AudioStream   *message);
size_t audio_stream__pack
                     (const AudioStream   *message,
                      uint8_t             *out);
size_t audio_stream__pack_to_buffer
                     (const AudioStream   *message,
                      ProtobufCBuffer     *buffer);
AudioStream *
       audio_stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio_stream__free_unpacked
                     (AudioStream *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Jit_Closure)
                 (const Jit *message,
                  void *closure_data);
typedef void (*MediaInfo_Closure)
                 (const MediaInfo *message,
                  void *closure_data);
typedef void (*Stream_Closure)
                 (const Stream *message,
                  void *closure_data);
typedef void (*AudioStream_Closure)
                 (const AudioStream *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    stream_type__descriptor;
extern const ProtobufCMessageDescriptor jit__descriptor;
extern const ProtobufCMessageDescriptor media_info__descriptor;
extern const ProtobufCMessageDescriptor stream__descriptor;
extern const ProtobufCMessageDescriptor audio_stream__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Jit_2eproto__INCLUDED */
