/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: JitControl.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "JitControl.pb-c.h"
void   jit_control__init
                     (JitControl         *message)
{
  static const JitControl init_value = JIT_CONTROL__INIT;
  *message = init_value;
}
size_t jit_control__get_packed_size
                     (const JitControl *message)
{
  assert(message->base.descriptor == &jit_control__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t jit_control__pack
                     (const JitControl *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &jit_control__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t jit_control__pack_to_buffer
                     (const JitControl *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &jit_control__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
JitControl *
       jit_control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (JitControl *)
     protobuf_c_message_unpack (&jit_control__descriptor,
                                allocator, len, data);
}
void   jit_control__free_unpacked
                     (JitControl *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &jit_control__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   seek_control__init
                     (SeekControl         *message)
{
  static const SeekControl init_value = SEEK_CONTROL__INIT;
  *message = init_value;
}
size_t seek_control__get_packed_size
                     (const SeekControl *message)
{
  assert(message->base.descriptor == &seek_control__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t seek_control__pack
                     (const SeekControl *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &seek_control__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t seek_control__pack_to_buffer
                     (const SeekControl *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &seek_control__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SeekControl *
       seek_control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SeekControl *)
     protobuf_c_message_unpack (&seek_control__descriptor,
                                allocator, len, data);
}
void   seek_control__free_unpacked
                     (SeekControl *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &seek_control__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor jit_control__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(JitControl, type),
    &control_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seek",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(JitControl, seek),
    &seek_control__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned jit_control__field_indices_by_name[] = {
  1,   /* field[1] = seek */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange jit_control__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor jit_control__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "JitControl",
  "JitControl",
  "JitControl",
  "",
  sizeof(JitControl),
  2,
  jit_control__field_descriptors,
  jit_control__field_indices_by_name,
  1,  jit_control__number_ranges,
  (ProtobufCMessageInit) jit_control__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor seek_control__field_descriptors[1] =
{
  {
    "position",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(SeekControl, position),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned seek_control__field_indices_by_name[] = {
  0,   /* field[0] = position */
};
static const ProtobufCIntRange seek_control__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor seek_control__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SeekControl",
  "SeekControl",
  "SeekControl",
  "",
  sizeof(SeekControl),
  1,
  seek_control__field_descriptors,
  seek_control__field_indices_by_name,
  1,  seek_control__number_ranges,
  (ProtobufCMessageInit) seek_control__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue control_type__enum_values_by_number[4] =
{
  { "PAUSE", "CONTROL_TYPE__PAUSE", 0 },
  { "PLAY", "CONTROL_TYPE__PLAY", 1 },
  { "SEEK", "CONTROL_TYPE__SEEK", 2 },
  { "QUIT", "CONTROL_TYPE__QUIT", 3 },
};
static const ProtobufCIntRange control_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex control_type__enum_values_by_name[4] =
{
  { "PAUSE", 0 },
  { "PLAY", 1 },
  { "QUIT", 3 },
  { "SEEK", 2 },
};
const ProtobufCEnumDescriptor control_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ControlType",
  "ControlType",
  "ControlType",
  "",
  4,
  control_type__enum_values_by_number,
  4,
  control_type__enum_values_by_name,
  1,
  control_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
