***************
*** 25,46 ****
  CFLAGS += -DCODECS
  endif
  
- CFLAGS+=-I../..
- 
- LDFLAGS+=-L../../framework
- 
- LDFLAGS+=-lavformat$(AVFORMAT_SUFFIX) -lavcodec$(AVFORMAT_SUFFIX) -lavutil$(AVFORMAT_SUFFIX) -lavdevice$(AVFORMAT_SUFFIX) $(EXTRA_LIBS) -lmlt
- 
  ifdef SWSCALE
- 	CFLAGS+=-DSWSCALE
- 	LDFLAGS+=-lswscale$(AVFORMAT_SUFFIX)
  endif
  
  ifdef LOCAL_FFMPEG
- 	LOCAL_FFMPEG_OBJS = ffmpeg/libavformat/libavformat$(AVFORMAT_SUFFIX) \
- 	                    ffmpeg/libavcodec/libavcodec$(AVFORMAT_SUFFIX) \
- 	                    ffmpeg/libavutil/libavutil$(AVFORMAT_SUFFIX) \
- 	                    ffmpeg/libavutil/libavdevice$(AVFORMAT_SUFFIX)
  endif
  
  SRCS := $(OBJS:.o=.c)
--- 35,50 ----
  CFLAGS += -DCODECS
  endif
  
  ifdef SWSCALE
+ CFLAGS += -DSWSCALE
+ LDFLAGS += -lswscale$(AVFORMAT_SUFFIX)
  endif
  
  ifdef LOCAL_FFMPEG
+ LOCAL_FFMPEG_OBJS = ffmpeg/libavformat/libavformat$(AVFORMAT_SUFFIX) \
+                     ffmpeg/libavcodec/libavcodec$(AVFORMAT_SUFFIX) \
+                     ffmpeg/libavutil/libavutil$(AVFORMAT_SUFFIX) \
+                     ffmpeg/libavutil/libavdevice$(AVFORMAT_SUFFIX)
  endif
  
  SRCS := $(OBJS:.o=.c)
