schema_version: 0.1
type: producer
identifier: ndi
title: NDI Input
creator: Maksym Veremeyenko
license: LGPLv2.1
language: en
tags:
  - Video
  - Network
description: Audio/Video over IP input using NewTek's NDI technology
parameters:
  - identifier: argument
    type: string
    title: NDI Source name
    description: Name of the NDI Source to receive
    required: yes
    mutable: no