schema_version: 7.2
type: producer
identifier: kdenlivetitle
title: Kdenlive Titler
version: 7
copyright: Marco Gittler, Jean-Baptiste Mardelle
creator: Marco Gittler, Jean-Baptiste Mardelle
license: LGPLv2.1
language: en
tags:
  - Video
image_formats:
  - rgba
