#!/bin/sh

path=`which python 2> /dev/null`

if [ $? = 0 ]
then
	# Change this as needed
	export PYTHON_INCLUDE=`python -c "import sys;print \"%s/include/python%d.%d\"%(sys.prefix,sys.version_info[0],sys.version_info[1])"`

	[ ! -d "$PYTHON_INCLUDE" ] && echo python development missing && exit 1

	ln -sf ../mltpp.i .

	# Invoke swig
	swig -c++ -I../../mlt++ `pkg-config mlt-framework --cflags` -python mltpp.i || exit $?

	# Compile the wrapper
	g++ -fPIC -D_GNU_SOURCE -c -rdynamic -pthread `pkg-config mlt-framework --cflags` -I$PYTHON_INCLUDE mlt_wrap.cxx || exit $?

	# Create the module
	gcc -shared mlt_wrap.o -L../../mlt++ -lmlt++ -o _mlt.so || exit $?
else
	echo Python not installed.
	exit 1
fi
