#!/bin/sh

path=`which tclsh 2>/dev/null`

if [ "$path" != "" ]
then
	ln -sf ../mltpp.i .

	# Invoke swig
	swig -c++ -I../../mlt++ `pkg-config mlt-framework --cflags` -tcl mltpp.i || exit 1

	# Compile the wrapper
	g++ -D_GNU_SOURCE -c -rdynamic -pthread -I../../mlt++ `pkg-config mlt-framework --cflags` mlt_wrap.cxx || exit 1

	# Create the module
	gcc -shared mlt_wrap.o -L../../mlt++ -lmlt++ -o mlt.so || exit 1
else
	echo "Unable to locate tclsh."
	exit 1
fi

