#!/bin/sh

path=`which tclsh 2>/dev/null`

if [ "$path" != "" ]
then
	ln -sf ../mltpp.i .

	# Invoke swig
	swig -c++ -I/usr/local/include/mlt++ `mlt-config --cflags` -tcl mltpp.i || exit 1

	# Compile the wrapper
	g++ -D_GNU_SOURCE -c -rdynamic -pthread -I/usr/local/include/mlt++ `mlt-config --cflags` mltpp_wrap.cxx || exit 1

	# Create the module
	ld -shared mltpp_wrap.o -lmlt++ -o mltpp.so || exit 1
else
	echo "Unable to locate tclsh."
	exit 1
fi

