schema_version: 7.2
type: producer
identifier: noise
title: Noise
version: 2
copyright: Meltytech, LLC
creator: Charles Yates
license: LGPLv2.1
language: en
tags:
  - Audio
  - Video
description: White noise producer
audio_formats:
  - s16
image_formats:
  - yuv422
