schema_version: 0.1
type: producer
identifier: noise
title: Noise
version: 1
copyright: Ushodaya Enterprises Limited
creator: Charles Yates
license: LGPLv2.1
language: en
tags:
  - Audio
  - Video
description: White noise producer
parameters:
  - identifier: in
    title: In point
    type: time
    description: Set the start time offset to use within the clip
    readonly: no
    mutable: no
    minimum: 0
    default: 0
    widget: timecode

  - identifier: out
    title: Out point
    type: time
    description: Set the ending time offset to use within the clip
    readonly: no
    minimum: 0
    mutable: no
    widget: timecode
    
  - identifier: fps
    title: Frame Rate
    type: double
    description: The output frame rate of the producer
    readonly: yes
    
  - identifier: aspect_ratio
    title: Aspect Ratio
    type: double
    description: The sample aspect ratio of the producer
    readonly: yes
    
  - identifier: length
    title: Length
    type: time
    description: The duration of the file (in frames)
    readonly: yes
    widget: timecode
