#!/bin/sh

[ \( -d PAL \) -a \( ! $0 -nt PAL/luma01.pgm \) ] && exit 0

for i in PAL NTSC
do
	mkdir -p $i
	[ "$i" == "PAL" ] && h=576 || h=480
	./luma -h $h -bpp 16 > $i/luma01.pgm
	./luma -h $h -bpp 16 -offset 32768 -dmirror 1 > $i/luma02.pgm
	./luma -h $h -bpp 16 -bands 8 -rband 1 > $i/luma03.pgm
	./luma -h $h -bpp 16 -hmirror 1 > $i/luma04.pgm
	./luma -h $h -bpp 16 -bands 576 -vmirror 1 > $i/luma05.pgm
	./luma -h $h -bpp 16 -bands 576 -vmirror 0 > $i/luma06.pgm
	./luma -h $h -bpp 16 -bands 8 -rband 0 > $i/luma07.pgm
	./luma -h $h -bpp 16 -offset 32768 -dmirror 1 -hmirror 1 > $i/luma08.pgm
	./luma -h $h -bpp 16 -bands 8 -rband 0 > $i/luma09.pgm
	./luma -h $h -bpp 16 -offset 32768 -dmirror 1 -flip 1 > $i/luma10.pgm
	./luma -h $h -bpp 16 -offset 32768 -dmirror 1 -quart 1 > $i/luma11.pgm
	./luma -h $h -bpp 16 -offset 32768 -dmirror 1 -quart 1 -flip 1 > $i/luma12.pgm
	./luma -h $h -bpp 16 -offset 32768 -dmirror 1 -quart 1 -pflop 1 > $i/luma13.pgm
	./luma -h $h -bpp 16 -offset 32768 -dmirror 1 -quart 1 -flip 1 -pflop 1 > $i/luma14.pgm
	./luma -h $h -bpp 16 -type 1 > $i/luma15.pgm
	./luma -h $h -bpp 16 -type 1 -bands 2 -rband 1 > $i/luma16.pgm
	./luma -h $h -bpp 16 -type 2 > $i/luma17.pgm
	./luma -h $h -bpp 16 -type 2 -quart 1 > $i/luma18.pgm
	./luma -h $h -bpp 16 -type 2 -quart 1 -flip 1 > $i/luma19.pgm
	./luma -h $h -bpp 16 -type 2 -quart 1 -bands 2 > $i/luma20.pgm
	./luma -h $h -bpp 16 -type 3 > $i/luma21.pgm
done
