#!/usr/bin/env ruby
require 'mkmf'
system( "ln -sf ../mltpp.i mltpp.i" )
system( "swig -c++ -ruby -I../../src `mlt-config --cflags` mltpp.i" )
$CFLAGS += " -I../../src `mlt-config --cflags`"
$LDFLAGS += " -L../../src -lmlt++"
create_makefile('mltpp')
system( 'make' )
